import { authClient } from "@features/auth/lib";
import { NeonAuthUIProvider } from "@neondatabase/auth/react/ui";
import { Link, useRouter } from "@tanstack/react-router";
import type { ReactNode } from "react";

const AuthProvider = ({ children }: { children: ReactNode }) => {
  const router = useRouter();

  return (
    <NeonAuthUIProvider
      authClient={authClient}
      navigate={(href) => router.navigate({ href })}
      replace={(href) => router.navigate({ href, replace: true })}
      Link={({ href, ...props }) => <Link to={href} {...props} />}
      // social={{ providers: ["google", "facebook", "microsoft"] }}
      // credentials={{ forgotPassword: true }}
      viewPaths={{
        SIGN_IN: "login",
        SIGN_OUT: "logout",
        SIGN_UP: "register",
        FORGOT_PASSWORD: "forgot",
        RESET_PASSWORD: "reset",
        MAGIC_LINK: "magic",
      }}
      localization={{
        // --- Error Messages & Status Codes ---
        INVALID_USERNAME_OR_PASSWORD: "اسم المستخدم أو كلمة المرور غير صالحة",
        EMAIL_NOT_VERIFIED: "البريد الإلكتروني غير مفعل",
        UNEXPECTED_ERROR: "حدث خطأ غير متوقع. يرجى المحاولة مرة أخرى",
        USERNAME_IS_ALREADY_TAKEN: "اسم المستخدم مأخوذ بالفعل",
        USERNAME_TOO_SHORT: "اسم المستخدم قصير جداً",
        USERNAME_TOO_LONG: "اسم المستخدم طويل جداً",
        INVALID_USERNAME: "اسم المستخدم غير صالح",
        OTP_NOT_ENABLED: "التحقق بخطوتين (OTP) غير مفعل",
        OTP_HAS_EXPIRED: "انتهت صلاحية رمز التحقق",
        TOTP_NOT_ENABLED: "رمز التحقق الزمني (TOTP) غير مفعل",
        TWO_FACTOR_NOT_ENABLED: "المصادقة الثنائية غير مفعلة",
        BACKUP_CODES_NOT_ENABLED: "أكواد النسخ الاحتياطي غير مفعلة",
        INVALID_BACKUP_CODE: "كود النسخ الاحتياطي غير صالح",
        INVALID_CODE: "الرمز غير صالح",
        TOO_MANY_ATTEMPTS_REQUEST_NEW_CODE: "محاولات كثيرة جداً. يرجى الانتظار قبل طلب رمز جديد",
        INVALID_TWO_FACTOR_COOKIE: "ملف تعريف ارتباط المصادقة الثنائية غير صالح",

        // --- Subscriptions (Commented Out) ---
        /*
        SUBSCRIPTION_NOT_FOUND: "الاشتراك غير موجود",
        SUBSCRIPTION_PLAN_NOT_FOUND: "خطة الاشتراك غير موجودة",
        ALREADY_SUBSCRIBED_PLAN: "أنت مشترك بالفعل في هذه الخطة",
        UNABLE_TO_CREATE_CUSTOMER: "تعذر إنشاء ملف العميل",
        FAILED_TO_FETCH_PLANS: "فشل جلب خطط الاشتراك",
        SUBSCRIPTION_NOT_ACTIVE: "الاشتراك غير نشط",
        SUBSCRIPTION_NOT_SCHEDULED_FOR_CANCELLATION: "الاشتراك غير جدولة للإلغاء",
        */

        EMAIL_VERIFICATION_REQUIRED: "يجب تفعيل البريد الإلكتروني أولاً",
        INVALID_PHONE_NUMBER: "رقم الهاتف غير صالح",
        PHONE_NUMBER_EXIST: "رقم الهاتف مستخدم بالفعل",
        INVALID_PHONE_NUMBER_OR_PASSWORD: "رقم الهاتف أو كلمة المرور غير صالحة",
        OTP_NOT_FOUND: "رمز التحقق غير موجود",
        OTP_EXPIRED: "انتهت صلاحية رمز التحقق",
        INVALID_OTP: "رمز التحقق غير صالح",
        PHONE_NUMBER_NOT_VERIFIED: "رقم الهاتف غير مفعل",
        CHALLENGE_NOT_FOUND: "لم يتم العثور على تحدي الأمان",
        YOU_ARE_NOT_ALLOWED_TO_REGISTER_THIS_PASSKEY: "غير مسموح لك بتسجيل مفتاح المرور هذا",
        FAILED_TO_VERIFY_REGISTRATION: "فشل التحقق من التسجيل",
        PASSKEY_NOT_FOUND: "مفتاح المرور غير موجود",
        AUTHENTICATION_FAILED: "فشلت عملية المصادقة",
        UNABLE_TO_CREATE_SESSION: "تعذر إنشاء جلسة عمل",
        FAILED_TO_UPDATE_PASSKEY: "فشل تحديث مفتاح المرور",
        INVALID_SESSION_TOKEN: "رمز الجلسة غير صالح",
        PASSWORD_COMPROMISED: "كلمة المرور هذه تم تسريبها سابقاً، يرجى اختيار كلمة أخرى",
        INVALID_OAUTH_CONFIGURATION: "إعدادات تسجيل الدخول الخارجي غير صالحة",
        INVALID_EMAIL: "البريد الإلكتروني غير صالح",
        USER_NOT_FOUND: "المستخدم غير موجود",
        TOO_MANY_ATTEMPTS: "محاولات كثيرة جداً. يرجى المحاولة لاحقاً",
        MISSING_SECRET_KEY: "المفتاح السري مفقود",
        SERVICE_UNAVAILABLE: "الخدمة غير متوفرة حالياً",
        VERIFICATION_FAILED: "فشل التحقق",
        MISSING_RESPONSE: "الرد مفقود",
        UNKNOWN_ERROR: "خطأ غير معروف",
        INVALID_METADATA_TYPE: "نوع البيانات الوصفية غير صالح",
        REFILL_AMOUNT_AND_INTERVAL_REQUIRED: "مبلغ التعبئة والفترة الزمنية مطلوبان",
        REFILL_INTERVAL_AND_AMOUNT_REQUIRED: "الفترة الزمنية ومبلغ التعبئة مطلوبان",
        USER_BANNED: "تم حظر هذا المستخدم",
        UNAUTHORIZED_SESSION: "جلسة غير مصرح بها",
        KEY_NOT_FOUND: "المفتاح غير موجود",
        KEY_DISABLED: "المفتاح معطل",
        KEY_EXPIRED: "انتهت صلاحية المفتاح",
        USAGE_EXCEEDED: "تم تجاوز حد الاستخدام",
        KEY_NOT_RECOVERABLE: "المفتاح غير قابل للاسترداد",
        EXPIRES_IN_IS_TOO_SMALL: "وقت انتهاء الصلاحية صغير جداً",
        EXPIRES_IN_IS_TOO_LARGE: "وقت انتهاء الصلاحية كبير جداً",
        INVALID_REMAINING: "القيمة المتبقية غير صالحة",
        INVALID_PREFIX_LENGTH: "طول البادئة غير صالح",
        INVALID_NAME_LENGTH: "طول الاسم غير صالح",
        METADATA_DISABLED: "البيانات الوصفية معطلة",
        RATE_LIMIT_EXCEEDED: "تم تجاوز معدل الاستخدام المسموح به",
        NO_VALUES_TO_UPDATE: "لا توجد قيم لتحديثها",
        KEY_DISABLED_EXPIRATION: "المفتاح معطل بسبب انتهاء الصلاحية",
        INVALID_API_KEY: "مفتاح API غير صالح",
        INVALID_USER_ID_FROM_API_KEY: "معرف مستخدم غير صالح من مفتاح API",
        INVALID_API_KEY_GETTER_RETURN_TYPE: "نوع الإرجاع لمستلم المفتاح غير صالح",
        SERVER_ONLY_PROPERTY: "هذه الخاصية خاصة بالخادم فقط",
        FAILED_TO_CREATE_USER: "فشل إنشاء المستخدم",
        COULD_NOT_CREATE_SESSION: "تعذر إنشاء الجلسة",
        ANONYMOUS_USERS_CANNOT_SIGN_IN_AGAIN_ANONYMOUSLY:
          "المستخدمون المجهولون لا يمكنهم تسجيل الدخول مجهولين مرة أخرى",
        USER_ALREADY_EXISTS: "المستخدم موجود بالفعل",
        YOU_CANNOT_BAN_YOURSELF: "لا يمكنك حظر نفسك",
        YOU_ARE_NOT_ALLOWED_TO_CHANGE_USERS_ROLE: "غير مسموح لك بتغيير دور المستخدم",
        YOU_ARE_NOT_ALLOWED_TO_CREATE_USERS: "ليس لديك صلاحية لإنشاء مستخدمين",
        YOU_ARE_NOT_ALLOWED_TO_LIST_USERS: "ليس لديك صلاحية لعرض قائمة المستخدمين",
        YOU_ARE_NOT_ALLOWED_TO_LIST_USERS_SESSIONS: "ليس لديك صلاحية لعرض جلسات المستخدمين",
        YOU_ARE_NOT_ALLOWED_TO_BAN_USERS: "ليس لديك صلاحية لحظر المستخدمين",
        YOU_ARE_NOT_ALLOWED_TO_IMPERSONATE_USERS: "ليس لديك صلاحية لتقمص هوية المستخدمين",
        YOU_ARE_NOT_ALLOWED_TO_REVOKE_USERS_SESSIONS: "ليس لديك صلاحية لإلغاء جلسات المستخدمين",
        YOU_ARE_NOT_ALLOWED_TO_DELETE_USERS: "ليس لديك صلاحية لحذف المستخدمين",
        YOU_ARE_NOT_ALLOWED_TO_SET_USERS_PASSWORD: "ليس لديك صلاحية لتعيين كلمة مرور للمستخدمين",
        BANNED_USER: "مستخدم محظور",
        FAILED_TO_CREATE_SESSION: "فشل إنشاء الجلسة",
        FAILED_TO_UPDATE_USER: "فشل تحديث بيانات المستخدم",
        FAILED_TO_GET_SESSION: "فشل الحصول على بيانات الجلسة",
        INVALID_PASSWORD: "كلمة المرور غير صالحة",
        INVALID_EMAIL_OR_PASSWORD: "البريد الإلكتروني أو كلمة المرور غير صالحة",
        SOCIAL_ACCOUNT_ALREADY_LINKED: "هذا الحساب الاجتماعي مرتبط بالفعل بحساب آخر",
        PROVIDER_NOT_FOUND: "مزود الخدمة غير موجود",
        INVALID_TOKEN: "الرمز غير صالح",
        ID_TOKEN_NOT_SUPPORTED: "رمز المعرف غير مدعوم",
        FAILED_TO_GET_USER_INFO: "فشل الحصول على معلومات المستخدم",
        USER_EMAIL_NOT_FOUND: "لم يتم العثور على البريد الإلكتروني للمستخدم",
        PASSWORD_TOO_SHORT: "كلمة المرور قصيرة جداً",
        PASSWORD_TOO_LONG: "كلمة المرور طويلة جداً",
        EMAIL_CAN_NOT_BE_UPDATED: "لا يمكن تحديث البريد الإلكتروني",
        CREDENTIAL_ACCOUNT_NOT_FOUND: "لم يتم العثور على حساب بيانات الاعتماد",
        SESSION_EXPIRED: "انتهت صلاحية الجلسة",
        FAILED_TO_UNLINK_LAST_ACCOUNT:
          "فشل إلغاء ربط الحساب الأخير. يجب أن يظل حساب واحد على الأقل",
        ACCOUNT_NOT_FOUND: "الحساب غير موجود",
        USER_ALREADY_HAS_PASSWORD: "المستخدم لديه كلمة مرور بالفعل",

        // --- General UI ---
        APP: "التطبيق",
        ACCOUNT: "الحساب",
        ACCOUNTS: "الحسابات",
        ACCOUNTS_DESCRIPTION: "إدارة حساباتك التي سجلت الدخول بها حالياً.",
        ACCOUNTS_INSTRUCTIONS: "سجل الدخول إلى حساب إضافي.",
        ADD_ACCOUNT: "إضافة حساب",
        ADD_PASSKEY: "إضافة مفتاح مرور",
        ALREADY_HAVE_AN_ACCOUNT: "لديك حساب بالفعل؟",
        AVATAR: "الصورة الشخصية",
        AVATAR_DESCRIPTION: "انقر على الصورة لرفع صورة مخصصة من ملفاتك.",
        AVATAR_INSTRUCTIONS: "الصورة الشخصية اختيارية ولكن نوصي بها بشدة.",
        BACKUP_CODE_REQUIRED: "كود النسخ الاحتياطي مطلوب",
        BACKUP_CODES: "أكواد النسخ الاحتياطي",
        BACKUP_CODES_DESCRIPTION:
          "احفظ أكواد النسخ الاحتياطي هذه في مكان آمن. يمكنك استخدامها للوصول إلى حسابك إذا فقدت وسيلة المصادقة الثنائية.",
        BACKUP_CODE_PLACEHOLDER: "كود النسخ الاحتياطي.",
        BACKUP_CODE: "كود النسخ الاحتياطي",
        CANCEL: "إلغاء",
        CHANGE_PASSWORD: "تغيير كلمة المرور",
        CHANGE_PASSWORD_DESCRIPTION: "أدخل كلمة المرور الحالية وكلمة المرور الجديدة.",
        CHANGE_PASSWORD_INSTRUCTIONS: "يرجى استخدام 8 رموز على الأقل.",
        CHANGE_PASSWORD_SUCCESS: "تم تغيير كلمة المرور بنجاح.",
        CONFIRM_PASSWORD: "تأكيد كلمة المرور",
        CONFIRM_PASSWORD_PLACEHOLDER: "تأكيد كلمة المرور",
        CONFIRM_PASSWORD_REQUIRED: "تأكيد كلمة المرور مطلوب",
        CONTINUE_WITH_AUTHENTICATOR: "المتابعة عبر تطبيق المصادقة",
        COPIED_TO_CLIPBOARD: "تم النسخ إلى الحافظة",
        COPY_TO_CLIPBOARD: "نسخ إلى الحافظة",
        COPY_ALL_CODES: "نسخ جميع الأكواد",
        CONTINUE: "متابعة",
        CURRENT_PASSWORD: "كلمة المرور الحالية",
        CURRENT_PASSWORD_PLACEHOLDER: "كلمة المرور الحالية",
        CURRENT_SESSION: "الجلسة الحالية",
        UPDATE: "تحديث",
        DELETE: "حذف",
        DELETE_AVATAR: "حذف الصورة الشخصية",
        DELETE_ACCOUNT: "حذف الحساب",
        DELETE_ACCOUNT_DESCRIPTION:
          "حذف حسابك وجميع محتوياته بشكل دائم. هذا الإجراء غير قابل للتراجع، يرجى المتابعة بحذر.",
        DELETE_ACCOUNT_INSTRUCTIONS: "يرجى تأكيد حذف حسابك. هذا الإجراء غير قابل للتراجع.",
        DELETE_ACCOUNT_VERIFY: "يرجى التحقق من بريدك الإلكتروني لتأكيد حذف الحساب.",
        DELETE_ACCOUNT_SUCCESS: "تم حذف حسابك بنجاح.",
        DISABLE_TWO_FACTOR: "تعطيل المصادقة الثنائية",
        DISABLED_CREDENTIALS_DESCRIPTION: "اختر مزوداً لتسجيل الدخول إلى حسابك",
        DONT_HAVE_AN_ACCOUNT: "ليس لديك حساب؟",
        DONE: "تم",
        EMAIL: "البريد الإلكتروني",
        EMAIL_DESCRIPTION: "أدخل البريد الإلكتروني الذي تريد استخدامه لتسجيل الدخول.",
        EMAIL_INSTRUCTIONS: "يرجى إدخال بريد إلكتروني صحيح.",
        EMAIL_IS_THE_SAME: "البريد الإلكتروني هو نفسه الحالي",
        EMAIL_PLACEHOLDER: "m@example.com",
        EMAIL_REQUIRED: "البريد الإلكتروني مطلوب",
        EMAIL_VERIFY_CHANGE: "يرجى التحقق من بريدك الإلكتروني لتأكيد التغيير.",
        EMAIL_VERIFICATION: "التحقق من البريد",
        // EMAIL_VERIFICATION_DESCRIPTION:
        //   "يرجى التحقق من بريدك الإلكتروني للحصول على رمز التفعيل لإكمال التسجيل.",
        // EMAIL_VERIFICATION_SUCCESS: "تم تفعيل البريد الإلكتروني بنجاح.",
        ENABLE_TWO_FACTOR: "تفعيل المصادقة الثنائية",
        IS_INVALID: "غير صالح",
        IS_REQUIRED: "مطلوب",
        IS_THE_SAME: "هو نفسه",
        FORGOT_AUTHENTICATOR: "فقدت تطبيق المصادقة؟",
        FORGOT_PASSWORD: "نسيت كلمة المرور",
        FORGOT_PASSWORD_ACTION: "إرسال رابط إعادة التعيين",
        FORGOT_PASSWORD_DESCRIPTION: "أدخل بريدك الإلكتروني لإعادة تعيين كلمة المرور",
        FORGOT_PASSWORD_EMAIL: "تحقق من بريدك للحصول على رابط إعادة تعيين كلمة المرور.",
        FORGOT_PASSWORD_LINK: "هل نسيت كلمة المرور؟",
        LINK: "ربط",
        MAGIC_LINK: "الرابط السحري",
        MAGIC_LINK_ACTION: "إرسال الرابط السحري",
        MAGIC_LINK_DESCRIPTION: "أدخل بريدك الإلكتروني لتلقي رابط تسجيل دخول مباشر",
        MAGIC_LINK_EMAIL: "تحقق من بريدك الإلكتروني للحصول على الرابط السحري",
        EMAIL_OTP: "كود البريد الإلكتروني",
        EMAIL_OTP_SEND_ACTION: "إرسال الكود",
        EMAIL_OTP_VERIFY_ACTION: "تأكيد الكود",
        EMAIL_OTP_DESCRIPTION: "أدخل بريدك الإلكتروني لتلقي كود التحقق",
        EMAIL_OTP_VERIFICATION_SENT: "يرجى التحقق من بريدك للحصول على كود التفعيل.",
        NAME: "الاسم",
        NAME_DESCRIPTION: "يرجى إدخال اسمك الكامل أو اسم العرض.",
        NAME_INSTRUCTIONS: "يرجى استخدام 32 رمزاً كحد أقصى.",
        NAME_PLACEHOLDER: "الاسم",
        NEW_PASSWORD: "كلمة المرور الجديدة",
        NEW_PASSWORD_PLACEHOLDER: "كلمة المرور الجديدة",
        NEW_PASSWORD_REQUIRED: "كلمة المرور الجديدة مطلوبة",
        ONE_TIME_PASSWORD: "كلمة مرور لمرة واحدة",
        OR_CONTINUE_WITH: "أو المتابعة باستخدام",
        PASSKEY: "مفتاح المرور",
        PASSKEYS: "مفاتيح المرور",
        PASSKEYS_DESCRIPTION: "إدارة مفاتيح المرور للوصول الآمن.",
        PASSKEYS_INSTRUCTIONS: "ادخل إلى حسابك بأمان دون كلمة مرور.",
        PERSONAL_ACCOUNT: "حساب شخصي",

        // --- API Keys ---
        API_KEYS: "مفاتيح API",
        API_KEYS_DESCRIPTION: "إدارة مفاتيح API الخاصة بك للوصول البرمجي.",
        API_KEYS_INSTRUCTIONS: "أنشئ مفاتيح API للوصول إلى حسابك برمجياً.",
        CREATE_API_KEY: "إنشاء مفتاح API",
        CREATE_API_KEY_DESCRIPTION: "أدخل اسماً فريداً لمفتاح API الخاص بك.",
        API_KEY_NAME_PLACEHOLDER: "مفتاح API جديد",
        API_KEY_CREATED: "تم إنشاء مفتاح API",
        CREATE_API_KEY_SUCCESS:
          "يرجى نسخ مفتاح API وحفظه في مكان آمن. لأسباب أمنية، لن نتمكن من إظهاره لك مرة أخرى.",
        NEVER_EXPIRES: "لا تنتهي صلاحيته",
        EXPIRES: "تنتهي الصلاحية",
        NO_EXPIRATION: "بدون تاريخ انتهاء",
        DELETE_API_KEY: "حذف مفتاح API",
        DELETE_API_KEY_CONFIRM: "هل أنت متأكد أنك تريد حذف مفتاح API هذا؟",
        API_KEY: "مفتاح API",

        // --- Passwords & Security ---
        PASSWORD: "كلمة المرور",
        PASSWORD_PLACEHOLDER: "كلمة المرور",
        PASSWORD_REQUIRED: "كلمة المرور مطلوبة",
        PASSWORDS_DO_NOT_MATCH: "كلمات المرور غير متطابقة",
        PROVIDERS: "مزودو الخدمة",
        PROVIDERS_DESCRIPTION: "ربط حسابك بخدمة خارجية.",
        RECOVER_ACCOUNT: "استعادة الحساب",
        RECOVER_ACCOUNT_ACTION: "استعادة الحساب",
        RECOVER_ACCOUNT_DESCRIPTION: "يرجى إدخال كود النسخ الاحتياطي للوصول إلى حسابك",
        REMEMBER_ME: "تذكرني",
        RESEND_CODE: "إعادة إرسال الكود",
        RESEND_VERIFICATION_EMAIL: "إعادة إرسال بريد التفعيل",
        RESET_PASSWORD: "إعادة تعيين كلمة المرور",
        RESET_PASSWORD_ACTION: "حفظ كلمة المرور الجديدة",
        RESET_PASSWORD_DESCRIPTION: "أدخل كلمة المرور الجديدة أدناه",
        RESET_PASSWORD_SUCCESS: "تم إعادة تعيين كلمة المرور بنجاح",
        SIGN_IN: "تسجيل الدخول",
        SIGN_IN_ACTION: "تسجيل الدخول",
        SIGN_IN_DESCRIPTION: "أدخل بريدك الإلكتروني أدناه لتسجيل الدخول",
        SIGN_IN_USERNAME_DESCRIPTION: "أدخل اسم المستخدم أو البريد الإلكتروني لتسجيل الدخول",
        SIGN_IN_WITH: "تسجيل الدخول بواسطة",
        SIGN_OUT: "تسجيل الخروج",
        SIGN_UP: "إنشاء حساب",
        SIGN_UP_ACTION: "إنشاء حساب",
        SIGN_UP_DESCRIPTION: "أدخل بياناتك لإنشاء حساب جديد",
        SIGN_UP_EMAIL: "تحقق من بريدك الإلكتروني للحصول على رابط التفعيل.",
        SESSIONS: "الجلسات",
        SESSIONS_DESCRIPTION: "إدارة جلساتك النشطة وإلغاء صلاحيات الوصول.",
        SET_PASSWORD: "تعيين كلمة المرور",
        SET_PASSWORD_DESCRIPTION:
          "انقر على الزر أدناه لتلقي بريد إلكتروني لتعيين كلمة مرور لحسابك.",
        SETTINGS: "الإعدادات",
        SAVE: "حفظ",
        SECURITY: "الأمان",
        SWITCH_ACCOUNT: "تبديل الحساب",
        TRUST_DEVICE: "الوثوق بهذا الجهاز",
        TWO_FACTOR: "المصادقة الثنائية",
        TWO_FACTOR_ACTION: "تأكيد الكود",
        TWO_FACTOR_DESCRIPTION: "يرجى إدخال كلمة المرور لمرة واحدة للمتابعة",
        TWO_FACTOR_CARD_DESCRIPTION: "أضف طبقة حماية إضافية لحسابك.",
        TWO_FACTOR_DISABLE_INSTRUCTIONS: "يرجى إدخال كلمة المرور لتعطيل المصادقة الثنائية.",
        TWO_FACTOR_ENABLE_INSTRUCTIONS: "يرجى إدخال كلمة المرور لتفعيل المصادقة الثنائية.",
        TWO_FACTOR_ENABLED: "تم تفعيل المصادقة الثنائية بنجاح",
        TWO_FACTOR_DISABLED: "تم تعطيل المصادقة الثنائية",
        TWO_FACTOR_PROMPT: "المصادقة الثنائية",
        TWO_FACTOR_TOTP_LABEL: "امسح رمز QR باستخدام تطبيق المصادقة الخاص بك",
        SEND_VERIFICATION_CODE: "إرسال كود التفعيل",
        UNLINK: "إلغاء الربط",
        UPDATED_SUCCESSFULLY: "تم التحديث بنجاح",
        USERNAME: "اسم المستخدم",
        USERNAME_DESCRIPTION: "أدخل اسم المستخدم الذي تريد استخدامه.",
        USERNAME_INSTRUCTIONS: "يرجى استخدام 32 رمزاً كحد أقصى.",
        USERNAME_PLACEHOLDER: "اسم المستخدم",
        OPTIONAL_BRACKETS: "(اختياري)",
        SIGN_IN_USERNAME_PLACEHOLDER: "اسم المستخدم أو البريد الإلكتروني",
        VERIFY_YOUR_EMAIL: "فعل بريدك الإلكتروني",
        VERIFY_YOUR_EMAIL_DESCRIPTION:
          "يرجى تفعيل بريدك. تحقق من صندوق الوارد. إذا لم يصلك البريد، انقر على الزر أدناه لإعادة الإرسال.",
        GO_BACK: "الرجوع",
        SESSION_NOT_FRESH: "انتهت صلاحية الجلسة الأمنية. يرجى تسجيل الدخول مرة أخرى.",
        UPLOAD_AVATAR: "رفع صورة",
        LOGO: "الشعار",
        LOGO_DESCRIPTION: "انقر على الشعار لرفع شعار مخصص من ملفاتك.",
        LOGO_INSTRUCTIONS: "الشعار اختياري ولكن نوصي به بشدة.",
        UPLOAD: "رفع",
        UPLOAD_LOGO: "رفع الشعار",
        DELETE_LOGO: "حذف الشعار",
        PRIVACY_POLICY: "سياسة الخصوصية",
        TERMS_OF_SERVICE: "شروط الخدمة",
        PROTECTED_BY_RECAPTCHA: "هذا الموقع محمي بواسطة reCAPTCHA.",
        BY_CONTINUING_YOU_AGREE: "بالمتابعة، أنت توافق على",
        USER: "المستخدم",
        UNKNOWN: "غير معروف",
      }}
      localizeErrors
    >
      {children}
    </NeonAuthUIProvider>
  );
};

export default AuthProvider;
