/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as ProtectedRouteImport } from './app/_protected'
import { Route as IndexRouteImport } from './app/index'
import { Route as ProtectedProfileIndexRouteImport } from './app/_protected/profile/index'
import { Route as MainAuthAuthPathnameRouteImport } from './app/_main/_auth/auth.$pathname'
import { Route as MainAuthAccountPathnameRouteImport } from './app/_main/_auth/account.$pathname'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedProfileIndexRoute = ProtectedProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => ProtectedRoute,
} as any)
const MainAuthAuthPathnameRoute = MainAuthAuthPathnameRouteImport.update({
  id: '/_main/_auth/auth/$pathname',
  path: '/auth/$pathname',
  getParentRoute: () => rootRouteImport,
} as any)
const MainAuthAccountPathnameRoute = MainAuthAccountPathnameRouteImport.update({
  id: '/_main/_auth/account/$pathname',
  path: '/account/$pathname',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile/': typeof ProtectedProfileIndexRoute
  '/account/$pathname': typeof MainAuthAccountPathnameRoute
  '/auth/$pathname': typeof MainAuthAuthPathnameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProtectedProfileIndexRoute
  '/account/$pathname': typeof MainAuthAccountPathnameRoute
  '/auth/$pathname': typeof MainAuthAuthPathnameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/_protected/profile/': typeof ProtectedProfileIndexRoute
  '/_main/_auth/account/$pathname': typeof MainAuthAccountPathnameRoute
  '/_main/_auth/auth/$pathname': typeof MainAuthAuthPathnameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/profile/' | '/account/$pathname' | '/auth/$pathname'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/profile' | '/account/$pathname' | '/auth/$pathname'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_protected/profile/'
    | '/_main/_auth/account/$pathname'
    | '/_main/_auth/auth/$pathname'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  MainAuthAccountPathnameRoute: typeof MainAuthAccountPathnameRoute
  MainAuthAuthPathnameRoute: typeof MainAuthAuthPathnameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/profile/': {
      id: '/_protected/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProtectedProfileIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_main/_auth/auth/$pathname': {
      id: '/_main/_auth/auth/$pathname'
      path: '/auth/$pathname'
      fullPath: '/auth/$pathname'
      preLoaderRoute: typeof MainAuthAuthPathnameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/_auth/account/$pathname': {
      id: '/_main/_auth/account/$pathname'
      path: '/account/$pathname'
      fullPath: '/account/$pathname'
      preLoaderRoute: typeof MainAuthAccountPathnameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedProfileIndexRoute: typeof ProtectedProfileIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedProfileIndexRoute: ProtectedProfileIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  MainAuthAccountPathnameRoute: MainAuthAccountPathnameRoute,
  MainAuthAuthPathnameRoute: MainAuthAuthPathnameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
