/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as PublicRouteImport } from './app/_public'
import { Route as AppRouteImport } from './app/_app'
import { Route as AdminIndexRouteImport } from './app/admin/index'
import { Route as AppNotificationsRouteImport } from './app/_app/notifications'
import { Route as AppMeRouteImport } from './app/_app/me'
import { Route as AppLibraryRouteImport } from './app/_app/library'
import { Route as AppDashboardRouteImport } from './app/_app/dashboard'
import { Route as PublicMarketingIndexRouteImport } from './app/_public/_marketing/index'
import { Route as AppSettingsIndexRouteImport } from './app/_app/settings/index'
import { Route as PublicUUserIdRouteImport } from './app/_public/u/$userId'
import { Route as PublicPublisherIdRouteImport } from './app/_public/publisher/$id'
import { Route as PublicDiscoverRecommendationsRouteImport } from './app/_public/discover/recommendations'
import { Route as PublicDiscoverPublishersRouteImport } from './app/_public/discover/publishers'
import { Route as PublicDiscoverGenresRouteImport } from './app/_public/discover/genres'
import { Route as PublicDiscoverBooksRouteImport } from './app/_public/discover/books'
import { Route as PublicDiscoverAuthorsRouteImport } from './app/_public/discover/authors'
import { Route as PublicBookIdRouteImport } from './app/_public/book/$id'
import { Route as PublicAuthorIdRouteImport } from './app/_public/author/$id'
import { Route as PublicAuthWelcomeRouteImport } from './app/_public/auth/welcome'
import { Route as PublicAuthPathnameRouteImport } from './app/_public/auth/$pathname'
import { Route as PublicAccountPathnameRouteImport } from './app/_public/account.$pathname'
import { Route as PublicMarketingTermsRouteImport } from './app/_public/_marketing/terms'
import { Route as PublicMarketingPrivacyRouteImport } from './app/_public/_marketing/privacy'
import { Route as PublicMarketingAboutRouteImport } from './app/_public/_marketing/about'
import { Route as AppSettingsSettingsRouteImport } from './app/_app/settings/settings'
import { Route as AppSettingsProfileRouteImport } from './app/_app/settings/profile'
import { Route as AppSettingsPrivacyRouteImport } from './app/_app/settings/privacy'
import { Route as AppSettingsImportExportRouteImport } from './app/_app/settings/import-export'
import { Route as AppSettingsAccountRouteImport } from './app/_app/settings/account'
import { Route as PublicPublisherIdBooksRouteImport } from './app/_public/publisher/$id.books'
import { Route as PublicPublisherIdArticlesRouteImport } from './app/_public/publisher/$id.articles'
import { Route as PublicAuthorIdSeriesRouteImport } from './app/_public/author/$id.series'
import { Route as PublicAuthorIdBooksRouteImport } from './app/_public/author/$id.books'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMeRoute = AppMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const PublicMarketingIndexRoute = PublicMarketingIndexRouteImport.update({
  id: '/_marketing/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const PublicUUserIdRoute = PublicUUserIdRouteImport.update({
  id: '/u/$userId',
  path: '/u/$userId',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPublisherIdRoute = PublicPublisherIdRouteImport.update({
  id: '/publisher/$id',
  path: '/publisher/$id',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDiscoverRecommendationsRoute =
  PublicDiscoverRecommendationsRouteImport.update({
    id: '/discover/recommendations',
    path: '/discover/recommendations',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicDiscoverPublishersRoute =
  PublicDiscoverPublishersRouteImport.update({
    id: '/discover/publishers',
    path: '/discover/publishers',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicDiscoverGenresRoute = PublicDiscoverGenresRouteImport.update({
  id: '/discover/genres',
  path: '/discover/genres',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDiscoverBooksRoute = PublicDiscoverBooksRouteImport.update({
  id: '/discover/books',
  path: '/discover/books',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDiscoverAuthorsRoute = PublicDiscoverAuthorsRouteImport.update({
  id: '/discover/authors',
  path: '/discover/authors',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBookIdRoute = PublicBookIdRouteImport.update({
  id: '/book/$id',
  path: '/book/$id',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAuthorIdRoute = PublicAuthorIdRouteImport.update({
  id: '/author/$id',
  path: '/author/$id',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAuthWelcomeRoute = PublicAuthWelcomeRouteImport.update({
  id: '/auth/welcome',
  path: '/auth/welcome',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAuthPathnameRoute = PublicAuthPathnameRouteImport.update({
  id: '/auth/$pathname',
  path: '/auth/$pathname',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAccountPathnameRoute = PublicAccountPathnameRouteImport.update({
  id: '/account/$pathname',
  path: '/account/$pathname',
  getParentRoute: () => PublicRoute,
} as any)
const PublicMarketingTermsRoute = PublicMarketingTermsRouteImport.update({
  id: '/_marketing/terms',
  path: '/terms',
  getParentRoute: () => PublicRoute,
} as any)
const PublicMarketingPrivacyRoute = PublicMarketingPrivacyRouteImport.update({
  id: '/_marketing/privacy',
  path: '/privacy',
  getParentRoute: () => PublicRoute,
} as any)
const PublicMarketingAboutRoute = PublicMarketingAboutRouteImport.update({
  id: '/_marketing/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const AppSettingsSettingsRoute = AppSettingsSettingsRouteImport.update({
  id: '/settings/settings',
  path: '/settings/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsProfileRoute = AppSettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsPrivacyRoute = AppSettingsPrivacyRouteImport.update({
  id: '/settings/privacy',
  path: '/settings/privacy',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsImportExportRoute = AppSettingsImportExportRouteImport.update({
  id: '/settings/import-export',
  path: '/settings/import-export',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsAccountRoute = AppSettingsAccountRouteImport.update({
  id: '/settings/account',
  path: '/settings/account',
  getParentRoute: () => AppRoute,
} as any)
const PublicPublisherIdBooksRoute = PublicPublisherIdBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => PublicPublisherIdRoute,
} as any)
const PublicPublisherIdArticlesRoute =
  PublicPublisherIdArticlesRouteImport.update({
    id: '/articles',
    path: '/articles',
    getParentRoute: () => PublicPublisherIdRoute,
  } as any)
const PublicAuthorIdSeriesRoute = PublicAuthorIdSeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => PublicAuthorIdRoute,
} as any)
const PublicAuthorIdBooksRoute = PublicAuthorIdBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => PublicAuthorIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicMarketingIndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/library': typeof AppLibraryRoute
  '/me': typeof AppMeRoute
  '/notifications': typeof AppNotificationsRoute
  '/admin/': typeof AdminIndexRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/import-export': typeof AppSettingsImportExportRoute
  '/settings/privacy': typeof AppSettingsPrivacyRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/settings/settings': typeof AppSettingsSettingsRoute
  '/about': typeof PublicMarketingAboutRoute
  '/privacy': typeof PublicMarketingPrivacyRoute
  '/terms': typeof PublicMarketingTermsRoute
  '/account/$pathname': typeof PublicAccountPathnameRoute
  '/auth/$pathname': typeof PublicAuthPathnameRoute
  '/auth/welcome': typeof PublicAuthWelcomeRoute
  '/author/$id': typeof PublicAuthorIdRouteWithChildren
  '/book/$id': typeof PublicBookIdRoute
  '/discover/authors': typeof PublicDiscoverAuthorsRoute
  '/discover/books': typeof PublicDiscoverBooksRoute
  '/discover/genres': typeof PublicDiscoverGenresRoute
  '/discover/publishers': typeof PublicDiscoverPublishersRoute
  '/discover/recommendations': typeof PublicDiscoverRecommendationsRoute
  '/publisher/$id': typeof PublicPublisherIdRouteWithChildren
  '/u/$userId': typeof PublicUUserIdRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/author/$id/books': typeof PublicAuthorIdBooksRoute
  '/author/$id/series': typeof PublicAuthorIdSeriesRoute
  '/publisher/$id/articles': typeof PublicPublisherIdArticlesRoute
  '/publisher/$id/books': typeof PublicPublisherIdBooksRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicMarketingIndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/library': typeof AppLibraryRoute
  '/me': typeof AppMeRoute
  '/notifications': typeof AppNotificationsRoute
  '/admin': typeof AdminIndexRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/import-export': typeof AppSettingsImportExportRoute
  '/settings/privacy': typeof AppSettingsPrivacyRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/settings/settings': typeof AppSettingsSettingsRoute
  '/about': typeof PublicMarketingAboutRoute
  '/privacy': typeof PublicMarketingPrivacyRoute
  '/terms': typeof PublicMarketingTermsRoute
  '/account/$pathname': typeof PublicAccountPathnameRoute
  '/auth/$pathname': typeof PublicAuthPathnameRoute
  '/auth/welcome': typeof PublicAuthWelcomeRoute
  '/author/$id': typeof PublicAuthorIdRouteWithChildren
  '/book/$id': typeof PublicBookIdRoute
  '/discover/authors': typeof PublicDiscoverAuthorsRoute
  '/discover/books': typeof PublicDiscoverBooksRoute
  '/discover/genres': typeof PublicDiscoverGenresRoute
  '/discover/publishers': typeof PublicDiscoverPublishersRoute
  '/discover/recommendations': typeof PublicDiscoverRecommendationsRoute
  '/publisher/$id': typeof PublicPublisherIdRouteWithChildren
  '/u/$userId': typeof PublicUUserIdRoute
  '/settings': typeof AppSettingsIndexRoute
  '/author/$id/books': typeof PublicAuthorIdBooksRoute
  '/author/$id/series': typeof PublicAuthorIdSeriesRoute
  '/publisher/$id/articles': typeof PublicPublisherIdArticlesRoute
  '/publisher/$id/books': typeof PublicPublisherIdBooksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/library': typeof AppLibraryRoute
  '/_app/me': typeof AppMeRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/admin/': typeof AdminIndexRoute
  '/_app/settings/account': typeof AppSettingsAccountRoute
  '/_app/settings/import-export': typeof AppSettingsImportExportRoute
  '/_app/settings/privacy': typeof AppSettingsPrivacyRoute
  '/_app/settings/profile': typeof AppSettingsProfileRoute
  '/_app/settings/settings': typeof AppSettingsSettingsRoute
  '/_public/_marketing/about': typeof PublicMarketingAboutRoute
  '/_public/_marketing/privacy': typeof PublicMarketingPrivacyRoute
  '/_public/_marketing/terms': typeof PublicMarketingTermsRoute
  '/_public/account/$pathname': typeof PublicAccountPathnameRoute
  '/_public/auth/$pathname': typeof PublicAuthPathnameRoute
  '/_public/auth/welcome': typeof PublicAuthWelcomeRoute
  '/_public/author/$id': typeof PublicAuthorIdRouteWithChildren
  '/_public/book/$id': typeof PublicBookIdRoute
  '/_public/discover/authors': typeof PublicDiscoverAuthorsRoute
  '/_public/discover/books': typeof PublicDiscoverBooksRoute
  '/_public/discover/genres': typeof PublicDiscoverGenresRoute
  '/_public/discover/publishers': typeof PublicDiscoverPublishersRoute
  '/_public/discover/recommendations': typeof PublicDiscoverRecommendationsRoute
  '/_public/publisher/$id': typeof PublicPublisherIdRouteWithChildren
  '/_public/u/$userId': typeof PublicUUserIdRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_public/_marketing/': typeof PublicMarketingIndexRoute
  '/_public/author/$id/books': typeof PublicAuthorIdBooksRoute
  '/_public/author/$id/series': typeof PublicAuthorIdSeriesRoute
  '/_public/publisher/$id/articles': typeof PublicPublisherIdArticlesRoute
  '/_public/publisher/$id/books': typeof PublicPublisherIdBooksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/library'
    | '/me'
    | '/notifications'
    | '/admin/'
    | '/settings/account'
    | '/settings/import-export'
    | '/settings/privacy'
    | '/settings/profile'
    | '/settings/settings'
    | '/about'
    | '/privacy'
    | '/terms'
    | '/account/$pathname'
    | '/auth/$pathname'
    | '/auth/welcome'
    | '/author/$id'
    | '/book/$id'
    | '/discover/authors'
    | '/discover/books'
    | '/discover/genres'
    | '/discover/publishers'
    | '/discover/recommendations'
    | '/publisher/$id'
    | '/u/$userId'
    | '/settings/'
    | '/author/$id/books'
    | '/author/$id/series'
    | '/publisher/$id/articles'
    | '/publisher/$id/books'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/library'
    | '/me'
    | '/notifications'
    | '/admin'
    | '/settings/account'
    | '/settings/import-export'
    | '/settings/privacy'
    | '/settings/profile'
    | '/settings/settings'
    | '/about'
    | '/privacy'
    | '/terms'
    | '/account/$pathname'
    | '/auth/$pathname'
    | '/auth/welcome'
    | '/author/$id'
    | '/book/$id'
    | '/discover/authors'
    | '/discover/books'
    | '/discover/genres'
    | '/discover/publishers'
    | '/discover/recommendations'
    | '/publisher/$id'
    | '/u/$userId'
    | '/settings'
    | '/author/$id/books'
    | '/author/$id/series'
    | '/publisher/$id/articles'
    | '/publisher/$id/books'
  id:
    | '__root__'
    | '/_app'
    | '/_public'
    | '/_app/dashboard'
    | '/_app/library'
    | '/_app/me'
    | '/_app/notifications'
    | '/admin/'
    | '/_app/settings/account'
    | '/_app/settings/import-export'
    | '/_app/settings/privacy'
    | '/_app/settings/profile'
    | '/_app/settings/settings'
    | '/_public/_marketing/about'
    | '/_public/_marketing/privacy'
    | '/_public/_marketing/terms'
    | '/_public/account/$pathname'
    | '/_public/auth/$pathname'
    | '/_public/auth/welcome'
    | '/_public/author/$id'
    | '/_public/book/$id'
    | '/_public/discover/authors'
    | '/_public/discover/books'
    | '/_public/discover/genres'
    | '/_public/discover/publishers'
    | '/_public/discover/recommendations'
    | '/_public/publisher/$id'
    | '/_public/u/$userId'
    | '/_app/settings/'
    | '/_public/_marketing/'
    | '/_public/author/$id/books'
    | '/_public/author/$id/series'
    | '/_public/publisher/$id/articles'
    | '/_public/publisher/$id/books'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/me': {
      id: '/_app/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AppMeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library': {
      id: '/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_public/_marketing/': {
      id: '/_public/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicMarketingIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_public/u/$userId': {
      id: '/_public/u/$userId'
      path: '/u/$userId'
      fullPath: '/u/$userId'
      preLoaderRoute: typeof PublicUUserIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/publisher/$id': {
      id: '/_public/publisher/$id'
      path: '/publisher/$id'
      fullPath: '/publisher/$id'
      preLoaderRoute: typeof PublicPublisherIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/discover/recommendations': {
      id: '/_public/discover/recommendations'
      path: '/discover/recommendations'
      fullPath: '/discover/recommendations'
      preLoaderRoute: typeof PublicDiscoverRecommendationsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/discover/publishers': {
      id: '/_public/discover/publishers'
      path: '/discover/publishers'
      fullPath: '/discover/publishers'
      preLoaderRoute: typeof PublicDiscoverPublishersRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/discover/genres': {
      id: '/_public/discover/genres'
      path: '/discover/genres'
      fullPath: '/discover/genres'
      preLoaderRoute: typeof PublicDiscoverGenresRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/discover/books': {
      id: '/_public/discover/books'
      path: '/discover/books'
      fullPath: '/discover/books'
      preLoaderRoute: typeof PublicDiscoverBooksRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/discover/authors': {
      id: '/_public/discover/authors'
      path: '/discover/authors'
      fullPath: '/discover/authors'
      preLoaderRoute: typeof PublicDiscoverAuthorsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/book/$id': {
      id: '/_public/book/$id'
      path: '/book/$id'
      fullPath: '/book/$id'
      preLoaderRoute: typeof PublicBookIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/author/$id': {
      id: '/_public/author/$id'
      path: '/author/$id'
      fullPath: '/author/$id'
      preLoaderRoute: typeof PublicAuthorIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/auth/welcome': {
      id: '/_public/auth/welcome'
      path: '/auth/welcome'
      fullPath: '/auth/welcome'
      preLoaderRoute: typeof PublicAuthWelcomeRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/auth/$pathname': {
      id: '/_public/auth/$pathname'
      path: '/auth/$pathname'
      fullPath: '/auth/$pathname'
      preLoaderRoute: typeof PublicAuthPathnameRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/account/$pathname': {
      id: '/_public/account/$pathname'
      path: '/account/$pathname'
      fullPath: '/account/$pathname'
      preLoaderRoute: typeof PublicAccountPathnameRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/_marketing/terms': {
      id: '/_public/_marketing/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PublicMarketingTermsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/_marketing/privacy': {
      id: '/_public/_marketing/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PublicMarketingPrivacyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/_marketing/about': {
      id: '/_public/_marketing/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicMarketingAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_app/settings/settings': {
      id: '/_app/settings/settings'
      path: '/settings/settings'
      fullPath: '/settings/settings'
      preLoaderRoute: typeof AppSettingsSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/profile': {
      id: '/_app/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AppSettingsProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/privacy': {
      id: '/_app/settings/privacy'
      path: '/settings/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof AppSettingsPrivacyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/import-export': {
      id: '/_app/settings/import-export'
      path: '/settings/import-export'
      fullPath: '/settings/import-export'
      preLoaderRoute: typeof AppSettingsImportExportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/account': {
      id: '/_app/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AppSettingsAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_public/publisher/$id/books': {
      id: '/_public/publisher/$id/books'
      path: '/books'
      fullPath: '/publisher/$id/books'
      preLoaderRoute: typeof PublicPublisherIdBooksRouteImport
      parentRoute: typeof PublicPublisherIdRoute
    }
    '/_public/publisher/$id/articles': {
      id: '/_public/publisher/$id/articles'
      path: '/articles'
      fullPath: '/publisher/$id/articles'
      preLoaderRoute: typeof PublicPublisherIdArticlesRouteImport
      parentRoute: typeof PublicPublisherIdRoute
    }
    '/_public/author/$id/series': {
      id: '/_public/author/$id/series'
      path: '/series'
      fullPath: '/author/$id/series'
      preLoaderRoute: typeof PublicAuthorIdSeriesRouteImport
      parentRoute: typeof PublicAuthorIdRoute
    }
    '/_public/author/$id/books': {
      id: '/_public/author/$id/books'
      path: '/books'
      fullPath: '/author/$id/books'
      preLoaderRoute: typeof PublicAuthorIdBooksRouteImport
      parentRoute: typeof PublicAuthorIdRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppMeRoute: typeof AppMeRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppSettingsAccountRoute: typeof AppSettingsAccountRoute
  AppSettingsImportExportRoute: typeof AppSettingsImportExportRoute
  AppSettingsPrivacyRoute: typeof AppSettingsPrivacyRoute
  AppSettingsProfileRoute: typeof AppSettingsProfileRoute
  AppSettingsSettingsRoute: typeof AppSettingsSettingsRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppMeRoute: AppMeRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppSettingsAccountRoute: AppSettingsAccountRoute,
  AppSettingsImportExportRoute: AppSettingsImportExportRoute,
  AppSettingsPrivacyRoute: AppSettingsPrivacyRoute,
  AppSettingsProfileRoute: AppSettingsProfileRoute,
  AppSettingsSettingsRoute: AppSettingsSettingsRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PublicAuthorIdRouteChildren {
  PublicAuthorIdBooksRoute: typeof PublicAuthorIdBooksRoute
  PublicAuthorIdSeriesRoute: typeof PublicAuthorIdSeriesRoute
}

const PublicAuthorIdRouteChildren: PublicAuthorIdRouteChildren = {
  PublicAuthorIdBooksRoute: PublicAuthorIdBooksRoute,
  PublicAuthorIdSeriesRoute: PublicAuthorIdSeriesRoute,
}

const PublicAuthorIdRouteWithChildren = PublicAuthorIdRoute._addFileChildren(
  PublicAuthorIdRouteChildren,
)

interface PublicPublisherIdRouteChildren {
  PublicPublisherIdArticlesRoute: typeof PublicPublisherIdArticlesRoute
  PublicPublisherIdBooksRoute: typeof PublicPublisherIdBooksRoute
}

const PublicPublisherIdRouteChildren: PublicPublisherIdRouteChildren = {
  PublicPublisherIdArticlesRoute: PublicPublisherIdArticlesRoute,
  PublicPublisherIdBooksRoute: PublicPublisherIdBooksRoute,
}

const PublicPublisherIdRouteWithChildren =
  PublicPublisherIdRoute._addFileChildren(PublicPublisherIdRouteChildren)

interface PublicRouteChildren {
  PublicMarketingAboutRoute: typeof PublicMarketingAboutRoute
  PublicMarketingPrivacyRoute: typeof PublicMarketingPrivacyRoute
  PublicMarketingTermsRoute: typeof PublicMarketingTermsRoute
  PublicAccountPathnameRoute: typeof PublicAccountPathnameRoute
  PublicAuthPathnameRoute: typeof PublicAuthPathnameRoute
  PublicAuthWelcomeRoute: typeof PublicAuthWelcomeRoute
  PublicAuthorIdRoute: typeof PublicAuthorIdRouteWithChildren
  PublicBookIdRoute: typeof PublicBookIdRoute
  PublicDiscoverAuthorsRoute: typeof PublicDiscoverAuthorsRoute
  PublicDiscoverBooksRoute: typeof PublicDiscoverBooksRoute
  PublicDiscoverGenresRoute: typeof PublicDiscoverGenresRoute
  PublicDiscoverPublishersRoute: typeof PublicDiscoverPublishersRoute
  PublicDiscoverRecommendationsRoute: typeof PublicDiscoverRecommendationsRoute
  PublicPublisherIdRoute: typeof PublicPublisherIdRouteWithChildren
  PublicUUserIdRoute: typeof PublicUUserIdRoute
  PublicMarketingIndexRoute: typeof PublicMarketingIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicMarketingAboutRoute: PublicMarketingAboutRoute,
  PublicMarketingPrivacyRoute: PublicMarketingPrivacyRoute,
  PublicMarketingTermsRoute: PublicMarketingTermsRoute,
  PublicAccountPathnameRoute: PublicAccountPathnameRoute,
  PublicAuthPathnameRoute: PublicAuthPathnameRoute,
  PublicAuthWelcomeRoute: PublicAuthWelcomeRoute,
  PublicAuthorIdRoute: PublicAuthorIdRouteWithChildren,
  PublicBookIdRoute: PublicBookIdRoute,
  PublicDiscoverAuthorsRoute: PublicDiscoverAuthorsRoute,
  PublicDiscoverBooksRoute: PublicDiscoverBooksRoute,
  PublicDiscoverGenresRoute: PublicDiscoverGenresRoute,
  PublicDiscoverPublishersRoute: PublicDiscoverPublishersRoute,
  PublicDiscoverRecommendationsRoute: PublicDiscoverRecommendationsRoute,
  PublicPublisherIdRoute: PublicPublisherIdRouteWithChildren,
  PublicUUserIdRoute: PublicUUserIdRoute,
  PublicMarketingIndexRoute: PublicMarketingIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
